# Generated by Django 4.0.5 on 2023-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_userinfo_password_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='emailid',
            field=models.CharField(max_length=50),
        ),
    ]
