# Generated by Django 4.0.5 on 2023-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_userinfo_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
